import FWCore.ParameterSet.Config as cms

inclusiveJetAnalyzer = cms.EDAnalyzer("HiInclusiveJetAnalyzer",
                                      jetTag = cms.InputTag("icPu5patJets"),
                                      subJetTag = cms.InputTag("ak4PFpatSubJetsWithBtagging"),
                                      jetPtMin = cms.double(5.0),
                                      matchTag = cms.untracked.InputTag("akPu3PFpatJets"),
                                      genjetTag = cms.InputTag("iterativeCone5HiGenJets"),
                                      eventInfoTag = cms.InputTag("generator"),
                                      genParticlesTag = cms.InputTag("HFdecayProductTagger"),
                                      isMC = cms.untracked.bool(False), 
                                      fillGenJets = cms.untracked.bool(False),
                                      rParam = cms.double(0.5),
                                      trackTag = cms.InputTag("hiTracks"),
                                      useHepMC = cms.untracked.bool(False),
                                      useQuality = cms.untracked.bool(True),
                                      trackQuality  = cms.untracked.string("highPurity"),
                                      useCentrality = cms.untracked.bool(False),
                                      doLifeTimeTagging = cms.untracked.bool(False),
                                      doLifeTimeTaggingExtra = cms.untracked.bool(False),
                                      doTrackMatching = cms.untracked.bool(True),
                                      doGenTaus = cms.untracked.bool(False),
                                      doSubJets = cms.untracked.bool(False),
                                      doJetConstituents = cms.untracked.bool(False),
				                      doWTARecluster = cms.untracked.bool(False),
                                      doHiJetID = cms.untracked.bool(False),
                                      doStandardJetID = cms.untracked.bool(False),
                                      doSubEvent = cms.untracked.bool(False),
                                      partonjetTag = cms.InputTag("ak4PartonJets"),
                                      groomedPartonJets = cms.InputTag("akSoftDrop4PartonJets")
                                      )
